# Training Parameters
lr0: 0.01  # initial learning rate
lrf: 0.01  # final one-cycle learning rate
momentum: 0.937  # optimizer momentum
weight_decay: 0.0005  # weight decay

# Data Augmentation
augmentation:
  hsv_h: 0.015  # image HSV-Hue augmentation (fraction)
  hsv_s: 0.7    # image HSV-Saturation augmentation (fraction)
  hsv_v: 0.4    # image HSV-Value augmentation (fraction)
  degrees: 10   # image rotation (+/- deg)
  translate: 0.1  # image translation (+/- fraction)
  scale: 0.5      # image scale (+/- gain)
  shear: 2         # image shear (+/- deg)
  perspective: 0.001  # image perspective (+/- fraction), range 0-0.001
  flipud: 0.0    # image flip up-down (probability)
  fliplr: 0.0    # image flip left-right (probability)
  mosaic: 1.0    # mosaic augmentation (probability)
  mixup: 0.5     # mixup augmentation (probability)
  copy_paste: 0.5  # copy-paste augmentation (probability)

# Learning Rate Scheduler
warmup_epochs: 3  # warmup epochs
warmup_momentum: 0.8  # warmup initial momentum
warmup_bias_lr: 0.1  # warmup initial bias LR

# Batch Size
batch_size: 16  # batch size for training

# Multi-Scale Training
multi_scale: False  # Use multi-scale training
img_size: 640  # image size for training

# Training Data
train_path: 'C:/path/to/train/images'  # Path to training images
val_path: 'C:/path/to/validation/images'  # Path to validation images
nc: 14  # Number of classes
names: ['class0', 'class1', ..., 'class13']  # Class names

# Anchor Settings
anchor_t: 4.0  # threshold for AutoAnchor
anchors: 0  # AutoAnchor will calculate anchors if set to 0

# Model
model_depth: 0  # Depth of the model
model_width: 0  # Width of the model
pretrained: True  # Use pre-trained weights
weights: 'yolov5s.pt'  # Base model weight

# Training Callbacks
save_period: 5  # Save model every n epochs
device: 'cuda:0'  # Device to train on (e.g., 'cuda:0' or 'cpu')
name: 'yolov5_training'  # Save folder name for checkpoints
project: 'runs'  # Project folder for saving checkpoints
exist_ok: True  # Overwrite existing checkpoints

# Evaluation
bbox_interval: 10  # Interval for evaluating bounding boxes
