_wandb:
    value:
        cli_version: 0.19.2
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 2
                - 1
                - 3
                - 12
                - 41
                - 49
                - 55
                - 105
            "2":
                - 2
                - 1
                - 3
                - 12
                - 41
                - 49
                - 55
                - 80
                - 105
            "3":
                - 2
                - 16
                - 23
                - 55
                - 62
            "4": 3.11.11
            "5": 0.19.2
            "8":
                - 5
            "12": 0.19.2
            "13": linux-x86_64
artifact_alias:
    value: latest
batch_size:
    value: 16
bbox_interval:
    value: -1
bucket:
    value: ""
cache:
    value: null
cfg:
    value: /content/yolov5/models/yolov5s.yaml
cos_lr:
    value: false
data:
    value: /content/path.yaml
device:
    value: ""
entity:
    value: null
epochs:
    value: 50
evolve:
    value: null
evolve_population:
    value: data/hyps
exist_ok:
    value: false
freeze:
    value:
        - 0
hyp:
    value:
        anchor_t: 4
        box: 0.05
        cls: 0.5
        cls_pw: 1
        copy_paste: 0.1
        degrees: 5
        fl_gamma: 0
        fliplr: 0
        flipud: 0
        grayscale: 0.5
        hsv_h: 0.015
        hsv_s: 1
        hsv_v: 0.4
        iou_t: 0.3
        lr0: 0.01
        lrf: 0.01
        mixup: 0.2
        momentum: 0.937
        mosaic: 0.5
        obj: 1
        obj_pw: 1
        perspective: 0.0005
        scale: 0.6
        shear: 15
        translate: 0.7
        warmup_bias_lr: 0.1
        warmup_epochs: 3
        warmup_momentum: 0.8
        weight_decay: 0.0005
image_weights:
    value: false
imgsz:
    value: 640
label_smoothing:
    value: 0
local_rank:
    value: -1
multi_scale:
    value: false
name:
    value: exp
ndjson_console:
    value: false
ndjson_file:
    value: false
noautoanchor:
    value: false
noplots:
    value: false
nosave:
    value: false
noval:
    value: false
optimizer:
    value: SGD
patience:
    value: 100
project:
    value: runs/train
quad:
    value: false
rect:
    value: false
resume:
    value: false
resume_evolve:
    value: null
save_dir:
    value: runs/train/exp
save_period:
    value: -1
seed:
    value: 0
single_cls:
    value: false
sync_bn:
    value: false
upload_dataset:
    value: false
weights:
    value: /content/yolov5/yolov5s.pt
workers:
    value: 8
